version: '3.8'

services:
  mcp-server:
    image: antpavlenkohmcorp/mcp-dockerized:latest
    container_name: mcp-server
    ports:
      - "8000:8000"
    environment:
      # Port configuration
      - MCPD_PORT=8000
      
      # Logging configuration
      - MCPD_LOG_LEVEL=INFO
      
      # API key configuration
      - MCPD_API_KEY_LENGTH=32
    
    volumes:
      # Persistent data storage
      - ./data:/app/data
      
      # Optional: Custom configuration
      # - ./config:/app/config
    
    restart: unless-stopped
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Security configuration
    security_opt:
      - no-new-privileges:true
    
    # Network configuration (optional)
    # networks:
    #   - mcp-network

# Optional: Custom network
# networks:
#   mcp-network:
#     driver: bridge

# Optional: Named volumes
# volumes:
#   mcp-data:
#     driver: local
